{{- $envName := include "app.toLower" .Values.environmentName -}}
{{- $appName := include "app.toLower" .Values.appName -}}
{{- $account := lower .Values.awsAccountAlias -}}

{{- if ne $account "sandbox" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
      environment: {{ $envName }}
  minAvailable: 2
{{- end }}